services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: urekoi
      POSTGRES_PASSWORD: urekoi
      POSTGRES_DB: urekoi
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: urekoi@example.com
      PGADMIN_DEFAULT_PASSWORD: urekoi
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  db_data:
