name: CI

on:
  pull_request:
    branches: [main]

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web
    env:
      APP_URL: http://localhost:3000
    steps:
      - uses: actions/checkout@v4 # checkout the repository

      - uses: pnpm/action-setup@v4 # setup pnpm

      - uses: actions/setup-node@v4 # setup node
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install --frozen-lockfile # install dependencies

      - run: pnpm exec playwright install --with-deps chromium # storybookのテストでchromiumを使うために必要

      - name: api-clientがopenapi.yamlと同期しているか確認
        run: |
          pnpm generate:api
          git diff --exit-code -- generated

      - run: pnpm format:check
      - run: pnpm lint
      - run: pnpm typecheck
      - run: pnpm test
      - run: pnpm build

  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/api
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: apps/api/go.mod

      - name: gofmt
        run: |
          unformatted=$(gofmt -l .)
          if [ -n "$unformatted" ]; then
            echo "$unformatted"
            exit 1
          fi

      - run: go vet ./...

      - uses: golangci/golangci-lint-action@v7 # インストールと実行までされる
        with:
          version: v2.12.2
          working-directory: apps/api

      - run: go test ./...

  # docs:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - uses: pnpm/action-setup@v4

  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: 22
  #         cache: pnpm

  #     - run: pnpm install --frozen-lockfile

  #     - run: pnpm docs:lint

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: reviewdog/action-actionlint@v1
